"""Initial migration

Revision ID: 7c65ca27edfc
Revises: f338aa8d1ba4
Create Date: 2023-10-08 17:28:04.924686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c65ca27edfc'
down_revision: Union[str, None] = 'f338aa8d1ba4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_activated')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_activated', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
